import { Update, Book } from "./types";

export const LATEST_UPDATES: Update[] = [
  {
    id: 1,
    title: "Madhyamik 2026 Exam Schedule Released by WBBSE",
    type: "Exam",
    date: "Feb 10",
  },
  {
    id: 2,
    title: "WB Govt Announces 5,000 New Teaching Positions",
    type: "Job",
    date: "Feb 8",
  },
  {
    id: 3,
    title: "HS 2025 Final Results Published — Check Now",
    type: "Result",
    date: "Feb 5",
  },
  {
    id: 4,
    title: "SVMCM Scholarship Application Deadline Extended",
    type: "Exam",
    date: "Feb 3",
  },
];

export const MOCK_BOOKS: Book[] = [
  {
    id: 1,
    title: "Class 10 History Master Guide",
    author: "YouTOP Academy",
    price: 199,
    originalPrice: 499,
    tag: "Best Seller",
    coverColor: "bg-brutal-purple",
    imageLink: "/images/mh.png",
    class: "10",
    subject: "History",
    description: "Complete preparation guide for Class 10 WBBSE History exam.",
  },
  {
    id: 2,
    title: "Class 12 Physics Formulas & Notes",
    author: "YouTOP Academy",
    price: 249,
    originalPrice: 599,
    tag: "New",
    coverColor: "bg-brutal-blue",
    imageLink: "/images/hs.png",
    class: "12",
    subject: "Physics",
    description:
      "Handwritten formula sheets and conceptual notes for HS Physics.",
  },
  {
    id: 3,
    title: "Class 8 Mathematics Solution Bank",
    author: "YouTOP Academy",
    price: 149,
    originalPrice: 349,
    tag: "Popular",
    coverColor: "bg-brutal-yellow",
    class: "8",
    subject: "Mathematics",
    description: "Step-by-step solutions for all complex math problems.",
  },
  {
    id: 4,
    title: "Class 6 Science Explorer",
    author: "YouTOP Academy",
    price: 129,
    originalPrice: 299,
    tag: "Trending",
    coverColor: "bg-brutal-green",
    class: "6",
    subject: "Science",
    description: "Interactive science guide with activities and diagrams.",
  },
  {
    id: 5,
    title: "Class 12 Bengali Sahitya Parichay",
    author: "YouTOP Academy",
    price: 179,
    originalPrice: 399,
    tag: "Best Seller",
    coverColor: "bg-brutal-purple",
    class: "12",
    subject: "Bengali",
    description: "Detailed analysis of poems and stories for WBCHSE Class 12.",
  },
  {
    id: 6,
    title: "Class 5 All Subject One-Shot",
    author: "YouTOP Academy",
    price: 99,
    originalPrice: 199,
    tag: "Budget",
    coverColor: "bg-brutal-blue",
    class: "5",
    subject: "All Subjects",
    description: "Simplified notes for all subjects of Class 5.",
  },
];
